services:
  db:
    image: postgres:15-alpine
    container_name: backpack_insight_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/DB/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Backend/PlayerData/Dockerfile
    container_name: backpack_insight_backend
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Backend:/app/Backend

  web:
    build:
      context: .
      dockerfile: Frontend/Web/Dockerfile
    container_name: backpack_insight_web
    restart: always

    ports:
      - "5080:5080"
    environment:
      - BACKEND_API_URL=http://backend:8000
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - ./Frontend/Web:/app/Frontend/Web

volumes:
  postgres_data:
  