"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-07 18:37:56.403255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemdefinition',
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('coin_value', sa.Integer(), nullable=True),
    sa.Column('item_types', sa.JSON(), nullable=True),
    sa.Column('connected_hero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unlock_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_shape', sa.JSON(), nullable=True),
    sa.Column('item_stars', sa.JSON(), nullable=True),
    sa.Column('purchasable', sa.Boolean(), nullable=False),
    sa.Column('recipes', sa.JSON(), nullable=True),
    sa.Column('combat_stats_data', sa.JSON(), nullable=True),
    sa.Column('all_stats_data', sa.JSON(), nullable=True),
    sa.Column('tooltips', sa.JSON(), nullable=True),
    sa.Column('levels_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    with op.batch_alter_table('itemdefinition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itemdefinition_connected_hero'), ['connected_hero'], unique=False)
        batch_op.create_index(batch_op.f('ix_itemdefinition_rarity'), ['rarity'], unique=False)

    op.create_table('profile',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trophies', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('gems', sa.Integer(), nullable=False),
    sa.Column('device_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technical_info_data', sa.JSON(), nullable=True),
    sa.Column('game_info_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_nickname'), ['nickname'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_trophies'), ['trophies'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_user_id'), ['user_id'], unique=False)

    op.create_table('hero',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('prestige', sa.Boolean(), nullable=False),
    sa.Column('league', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hero_rating'), ['rating'], unique=False)

    op.create_table('item',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('definition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('cards', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['itemdefinition.item_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_rating'))
        batch_op.drop_index(batch_op.f('ix_hero_name'))

    op.drop_table('hero')
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_trophies'))
        batch_op.drop_index(batch_op.f('ix_profile_nickname'))
        batch_op.drop_index(batch_op.f('ix_profile_level'))

    op.drop_table('profile')
    with op.batch_alter_table('itemdefinition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itemdefinition_rarity'))
        batch_op.drop_index(batch_op.f('ix_itemdefinition_connected_hero'))

    op.drop_table('itemdefinition')
    # ### end Alembic commands ###
